#!/usr/bin/env bash
#Script to create an RSA Key Pair with a key length of 4096 bits and save it to ~/.ssh/school with a passphrase.

#ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N "betty"
#Uncomment and run the command below to create the key pair| Comment out the above command.
ssh-keygen -t rsa -b 4096 -C "Optional comment" -f school -N "betty"