#!/usr/bin/env bash
# Script to install Apache2, create Hello Holberton page, and start Apache

apt-get update
apt-get install -y apache2
echo "Hello Holberton" > /var/www/html/index.html
service apache2 start
